sequenceDiagram
Title: DID Create attribute

participant Subject as DID Subject
participant API as API-Appnet
participant Database as Database
participant DIDSDK as DID SDK
participant HCS as Hedera HCS

note over Subject,HCS: Create an attribute
Subject ->> API: Send create event to endpoint (Secured by HTTP Signature)
API ->> API: Check Message Signing in HTTP Header
API ->> Database: Resolve DID through Projection
Database ->> API: Receive DID Document
API ->> API: Check Signature message signing with Delegate Key of DID Document
alt Signature validation fails
API ->> Subject: Return Response Message "Not Authorised"
else Signature validation success
API ->> DIDSDK: Create Event
DIDSDK ->> HCS: Register Event
HCS ->> DIDSDK: Ack
DIDSDK ->> API: Ack
API ->> Database: Add create event to EventStore
API ->> Database: Generate projection
API ->> Subject: Return Response Message
end