sequenceDiagram
Title: DID Claim ownership

participant user as user
participant API as Appnet
participant DB as Database
participant SDK as DID JS SDK


note over user, SDK: Claim DID Document ownership back from the AppNet. Changes DID root key to the one provided via `privateKeyMultibase` parameter.
user ->> API: Send multibase private key
alt auth
API ->> API: Check payload digest
API ->> DB: Retrieve DID Event messages
API ->> API: Resolve DID Document
API ->> API: Verify signature using <br> resolved DID Document Delegate Key
end 
alt auth fails
API ->> user: Return Response Message "Not Authorised"
else auth success
API ->> DB: Find DidKeypair
DB ->> API: Resolve DidKeypair
API ->> SDK: Create new DID owner Event with provided multibase private key 
SDK ->> API: ACK 
API ->> DB: Add DID owner change event to database
API ->> DB: Remove previous DidKeypair
API ->> API: Resolve DID
API ->> user: Return DID Document
end
