sequenceDiagram
Title: DID Update attribute

participant Subject as User
participant API as API-Appnet
participant Database as Database
participant DIDSDK as DID SDK

note over Subject,DIDSDK: Update an attribute
Subject ->> API: Send Update event to endpoint (Secured by HTTP Signature)
API ->> API: Check Message Signing in HTTP Header
API ->> Database: Resolve DID through Projection
Database ->> API: Receive DID Document
API ->> API: Check Signature message signing with Delegate Key of DID Document
alt Signature validation fails
API ->> Subject: Return Response Message "Not Authorised"
else Signature validation success
API ->> Database: Find DidKeypair
Database ->> API: Resolve DidKeypair
API ->> DIDSDK: Send Update Event
DIDSDK ->> API: Ack
API ->> Database: Add Update event to EventStore
API ->> Subject: Return DID Document
end