sequenceDiagram

participant Subject as DID Subject
participant API as API-Appnet
participant Database as Database
participant DIDSDK as DID SDK
participant HCS as Hedera HCS

note over Subject,Database: Claim ownership
Subject ->> API: Send the DID that you want to claim ownership on (Secured by HTTP Signature)
API ->> API: Check Message Signing in HTTP Header
API ->> Database: Resolve DID through Projection
Database ->> API: Receive DID Document
API ->> API: Check Signature message signing with Delegate Key of DID Document
alt Signature validation fails
API ->> Subject: Return Response Message "Not Authorised"
else Signature validation success
API ->> DIDSDK: Revoke VerificationRelationship event
DIDSDK ->> HCS: Revoke VerificationRelationship event
HCS ->> DIDSDK: Ack
DIDSDK ->> API: Ack
API ->> Database: Add Create VerificationRelationship event to EventStore
API ->> Database: Generate projection
API ->> DIDSDK:  Update DIDOwner Event  (Register the Delegate-key as the new Root-key)
DIDSDK ->> HCS:  Update DIDOwner Event
HCS ->> DIDSDK: Ack
DIDSDK ->> API: Ack
API ->> Database: add Update DIDOnwer Event  to EventStore
API ->> Database: Generate projection
API ->> Subject: Return Admin Key and Submit Key
end